################################################################################
# SWA Docker Compose
# Run the local development stack
################################################################################

version: "3"

services:
  node-red:
    image: fnyffene/swa-meshup:latest
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Bern
    ports:
      - "1880:1880"
    networks:
      - swa-net
    volumes:
      - .:/data
      - READATA:/rea-data
    env_file:
      - .env
  macromodel: 
    image: fnyffene/swa-macromodel:latest
    build: https://github.com/nyfelix/swa-macromodel.git
    environment:
      - TZ=Europe/Bern
    ports:
      - "5000:5000"
    volumes:
      # Only needed, when debugging macromodel and meshup,
      # assuming swa-meshup and swa-macromodel are in the same parent directory
      # - ../swa-macromodel:/webservice
      # - ../swa-macromodel/model-mockup:/model
      - READATA:/rea-data
    networks:
      - swa-net
  influx:
    image: influxdb:latest
    environment:
      - TZ=Europe/Bern
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
    networks:
      - swa-net
  chronograf:
    image: chronograf:latest
    environment:
      - TZ=Europe/Bern
    ports:
      - "8888:8888"
    networks:
      - swa-net
volumes:
  READATA:
  influxdb:

networks:
  swa-net: